### ISSUE TITLE
作者，你好，遇到一个问题，请教下。

### ISSUE THREAD

**Issue by weirui88888** [chansee97/nuxt-blog#3]
clone下来项目之后，安装完依赖之后，执行npm run dev后报错
![image](https://github.com/chansee97/nuxt-blog/assets/23164664/ae40f3e9-f3db-458a-a865-695ea2d252e4)
一直找不到具体原因是什么，我看网上有个类似的[issue](https://github.com/nuxt/content/issues/1562),按照issue提示操作之后，一直不太对。

**Comment by chansee97** [comment]
看上去是依赖问题，我看issue中清除lock文件重新安装依赖，试一试，我自己没有遇到这样的问题
